### ISSUE TITLE
Error when running composer require laravelhungary/announcement

### ISSUE THREAD

**Issue by w00p** [laravelhungary/announcement#1]
`[InvalidArgumentException]
  Could not find package laravelhungary/announcement at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

**Comment by hocza** [comment]
My bad, sorry.

Forgot to create a release. Now it is available as 1.0.0 

Try again. :)

**Comment by w00p** [comment]
Works, thank you :)

**Comment by hocza** [comment]
Cheers. Thanks for feedback.

I totally forgot that I was working with the "dev" :)
