### ISSUE TITLE
[New Feature] broadcast announce msgs through Echo.

### ISSUE THREAD

**Issue by ctf0** [laravelhungary/announcement#4]
what do u think of adding an option to flash the msg through Echo ?,

maybe something like `Announce::broadcast($type,$title,$message,$ttl)` and this method fires an event to a public channel then the user catches it with the client.

**Comment by ctf0** [comment]
check https://github.com/ctf0/announcement/tree/announcement-broadcasting

**Comment by hocza** [comment]
I just had to time to look thru it. 

Wow cool. :) 👍

**Comment by hocza** [comment]
It might be a good idea to add a broadcast to the create function.

``` php
public static function create($type = 'info', $title = '', $message = '', $ttl = 60, $broadcast = false, $channel_name = 'public-announcement-channel')
    {
        $announcement = new Announcement($type, $title, $message, $ttl);
        $announcement->save();
        if($broadcast)
            event(new NewAnnouncement($type, $title, $message, $ttl, $channel_name));
    }
```

By doing it like this, It won't be a breaking change.

**Comment by hocza** [comment]
However at this point it might be a great idea to make 'public-announcement-channel' a config variable, so they can change the default for only the broadcast or for the Create (with broadcast) :)

**Comment by ctf0** [comment]
the thing is , if we added to create 2 things happen
1- the method props become too much
2- the create method become cluttered with more than one responsibility

so having a separate method just for broadcasting makes it clear that this method needs slightly extra work from the user part

**Comment by ctf0** [comment]
+1 for the broadcast channel config

**Comment by ctf0** [comment]
honestly i wanted to make a one big solution, where the user doesnt need to care about anything other than calling `@broadcast` and assign the tag into the view file, but currently this is not possible as it needs lots of things to be modified

**Comment by ctf0** [comment]
i just had a :bulb: which will make things even easier,i will update the branch later today

**Comment by ctf0** [comment]
check the branch again, also updated the rdme to reflect the steps needs to use the broadcasting feature.

**Comment by hocza** [comment]
Cool.

However I do not see that you're using the newly added config key:

'broadcasting_channel' => env('ANNOUNCEMENTS-CHANNEL', 'public-announcement-channel'),

But you're calling the `$channel_name = env('ANNOUNCEMENTS-CHANNEL');` directly instead of `config('announcement.broadcasting_channel')`

**Comment by ctf0** [comment]
oh, okay i will change that, btw do u know a way to shorten the component path ?

**Comment by ctf0** [comment]
i made some refactoring + some temp changes till i figure out a proper way of making it more dynamic

**Comment by ctf0** [comment]
any news ?

**Comment by hocza** [comment]
Huh, on what? :)

The component path?

**Comment by ctf0** [comment]
adding it to the main branch ?, its mostly done unless u know a way to share the config value to js

**Comment by hocza** [comment]
Well I guess only with this little trick:

By requiring the developer to create a JS variable, like: laravel.announcement = {...};

Then in the separate .js file you can read the variable.

Or the other way I mostly use is creating a route, that return a JSON response.

``` php
Route::get('/lang/javascript/{item}', function ($item) {
    return trans('javascript.'.$item);
});
```

Same can be done with config. :) 

---

Anyway, you can make a pull request

**Comment by ctf0** [comment]
i was thinking of something like https://github.com/laracasts/PHP-Vars-To-Js-Transformer which will make things as we want but it will add extra load to the package

**Comment by ctf0** [comment]
anyhow i made some changes https://github.com/ctf0/announcement/tree/announcement-broadcasting check it out before i send the PR

**Comment by hocza** [comment]
Okay, it seems cool.
